FROM php:8.3.2-fpm-bookworm

RUN apt-get update \
        && apt-get install -y \
            bash \
            curl \
            ca-certificates \
            gnupg \
            git \
            npm \
            unzip \
            libzip-dev \
            libpng-dev \
            autoconf \
            busybox-static \
        && git clone https://github.com/phpredis/phpredis.git /usr/src/php/ext/redis \
        && docker-php-ext-install \
            zip \
            pdo_mysql \
            sockets \
            redis \
        && docker-php-ext-enable opcache

COPY --from=composer:2.6.6 /usr/bin/composer /usr/bin/composer

RUN mkdir -p /etc/apt/keyrings \
        && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key \
            | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
        && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" \
            | tee /etc/apt/sources.list.d/nodesource.list \
        && apt-get update \
        && apt-get install -y nodejs

RUN mkdir /app
WORKDIR /app
