FROM php:8.3.2-fpm-alpine3.19

RUN apk --update --no-cache add \
            bash \
            curl \
            ca-certificates \
            gnupg \
            git \
            npm \
            unzip \
            libzip-dev \
            libpng-dev \
            autoconf \
            busybox-static \
            linux-headers \
            nodejs~=20 \
        && git clone https://github.com/phpredis/phpredis.git /usr/src/php/ext/redis \
        && docker-php-ext-install \
            zip \
            pdo_mysql \
            sockets \
            redis \
        && docker-php-ext-enable opcache \
        && rm -rf /var/cache/apk/*

COPY --from=composer:2.6.6 /usr/bin/composer /usr/bin/composer

RUN mkdir /app
WORKDIR /app
